import React from "react";
import SimpleTable from "./components/SimpleTable";

interface MockData {
  date_time: string;
  email: string;
  first_name: string;
  last_name: string;
  gender: string;
  id: number;
}
const mockData2 = [
  {
    id: "4",
    date_time: "2021-10-10 09:33:39",
    first_name: "Ophelia",
    last_name: "Pala",
    email: "opala0@nature.com",
    gender: "Polygender",
  },
  {
    id: "9",
    date_time: "2021-10-02 04:25:32",
    first_name: "Sybilla",
    last_name: "Ledbetter",
    email: "sledbetter1@craigslist.org",
    gender: "Non-binary",
  },
  {
    id: "1",
    date_time: "2021-06-09 05:21:02",
    first_name: "Artemas",
    last_name: "Windsor",
    email: "awindsor2@washingtonpost.com",
    gender: "Agender",
  },
  {
    id: "1",
    date_time: "2021-08-24 18:47:20",
    first_name: "Philis",
    last_name: "Everleigh",
    email: "peverleigh3@cornell.edu",
    gender: "Genderqueer",
  },
  {
    id: "9",
    date_time: "2021-06-05 00:27:55",
    first_name: "Hadrian",
    last_name: "Flight",
    email: "hflight4@addtoany.com",
    gender: "Female",
  },
  {
    id: "5",
    date_time: "2021-04-29 17:52:52",
    first_name: "Wilhelm",
    last_name: "Digby",
    email: "wdigby5@omniture.com",
    gender: "Genderfluid",
  },
  {
    id: "0",
    date_time: "2021-07-22 22:29:43",
    first_name: "Clary",
    last_name: "Praundl",
    email: "cpraundl6@about.com",
    gender: "Genderqueer",
  },
  {
    id: "0",
    date_time: "2021-02-14 10:30:31",
    first_name: "Annice",
    last_name: "Dautry",
    email: "adautry7@youku.com",
    gender: "Agender",
  },
  {
    id: "0",
    date_time: "2021-07-24 17:17:41",
    first_name: "Sullivan",
    last_name: "Lamburne",
    email: "slamburne8@bravesites.com",
    gender: "Polygender",
  },
  {
    id: "3",
    date_time: "2021-08-01 01:18:52",
    first_name: "Hymie",
    last_name: "Garroway",
    email: "hgarroway9@abc.net.au",
    gender: "Genderfluid",
  },
  {
    id: "0",
    date_time: "2020-12-08 04:09:58",
    first_name: "Gigi",
    last_name: "Dondon",
    email: "gdondona@netvibes.com",
    gender: "Female",
  },
  {
    id: "8",
    date_time: "2021-09-19 21:51:37",
    first_name: "Pavlov",
    last_name: "Paulillo",
    email: "ppaulillob@ox.ac.uk",
    gender: "Genderfluid",
  },
  {
    id: "0",
    date_time: "2021-07-10 17:37:28",
    first_name: "Robby",
    last_name: "Ryce",
    email: "rrycec@t-online.de",
    gender: "Bigender",
  },
  {
    id: "7",
    date_time: "2021-03-25 03:57:00",
    first_name: "Rora",
    last_name: "Sharville",
    email: "rsharvilled@nps.gov",
    gender: "Bigender",
  },
  {
    id: "3",
    date_time: "2021-03-10 04:01:40",
    first_name: "Chalmers",
    last_name: "Hambers",
    email: "chamberse@whitehouse.gov",
    gender: "Bigender",
  },
  {
    id: "0",
    date_time: "2021-09-11 05:57:32",
    first_name: "Zulema",
    last_name: "Synnott",
    email: "zsynnottf@youtu.be",
    gender: "Agender",
  },
  {
    id: "6",
    date_time: "2021-09-21 00:51:20",
    first_name: "Merla",
    last_name: "McCarl",
    email: "mmccarlg@dell.com",
    gender: "Agender",
  },
  {
    id: "1",
    date_time: "2021-11-09 23:17:48",
    first_name: "Ahmad",
    last_name: "Keeble",
    email: "akeebleh@is.gd",
    gender: "Agender",
  },
  {
    id: "9",
    date_time: "2021-10-09 03:40:28",
    first_name: "Darelle",
    last_name: "Witchell",
    email: "dwitchelli@nationalgeographic.com",
    gender: "Genderqueer",
  },
  {
    id: "6",
    date_time: "2021-03-21 18:32:14",
    first_name: "Orlando",
    last_name: "Jorcke",
    email: "ojorckej@blogspot.com",
    gender: "Genderqueer",
  },
  {
    id: "6",
    date_time: "2021-10-11 19:58:58",
    first_name: "Arnaldo",
    last_name: "Smidmoor",
    email: "asmidmoork@amazon.com",
    gender: "Female",
  },
  {
    id: "7",
    date_time: "2021-11-09 22:40:50",
    first_name: "Edee",
    last_name: "Halton",
    email: "ehaltonl@ucsd.edu",
    gender: "Agender",
  },
  {
    id: "2",
    date_time: "2021-08-18 07:49:31",
    first_name: "Beatriz",
    last_name: "Eales",
    email: "bealesm@google.ru",
    gender: "Male",
  },
  {
    id: "4",
    date_time: "2021-10-16 14:24:48",
    first_name: "Tatiana",
    last_name: "Morrissey",
    email: "tmorrisseyn@blog.com",
    gender: "Genderfluid",
  },
  {
    id: "7",
    date_time: "2020-12-19 17:21:53",
    first_name: "Aldric",
    last_name: "Mathet",
    email: "amatheto@baidu.com",
    gender: "Non-binary",
  },
  {
    id: "6",
    date_time: "2021-03-23 15:54:00",
    first_name: "Chad",
    last_name: "Emblen",
    email: "cemblenp@army.mil",
    gender: "Male",
  },
  {
    id: "1",
    date_time: "2021-09-09 21:05:01",
    first_name: "Valene",
    last_name: "Stow",
    email: "vstowq@bravesites.com",
    gender: "Genderfluid",
  },
  {
    id: "4",
    date_time: "2021-06-19 16:20:36",
    first_name: "Ethelda",
    last_name: "Arstingall",
    email: "earstingallr@ovh.net",
    gender: "Genderqueer",
  },
  {
    id: "3",
    date_time: "2021-08-01 03:57:58",
    first_name: "Savina",
    last_name: "Jaggs",
    email: "sjaggss@economist.com",
    gender: "Male",
  },
  {
    id: "0",
    date_time: "2021-09-09 07:12:38",
    first_name: "Cynthy",
    last_name: "Tearney",
    email: "ctearneyt@guardian.co.uk",
    gender: "Female",
  },
  {
    id: "2",
    date_time: "2021-06-06 11:45:36",
    first_name: "Josiah",
    last_name: "Ewbank",
    email: "jewbanku@t-online.de",
    gender: "Agender",
  },
  {
    id: "4",
    date_time: "2021-10-30 07:35:13",
    first_name: "Tabby",
    last_name: "Tretwell",
    email: "ttretwellv@ameblo.jp",
    gender: "Genderqueer",
  },
  {
    id: "2",
    date_time: "2021-12-02 23:43:51",
    first_name: "Benn",
    last_name: "Kennett",
    email: "bkennettw@washington.edu",
    gender: "Agender",
  },
  {
    id: "4",
    date_time: "2021-04-14 02:15:20",
    first_name: "Moss",
    last_name: "Foxley",
    email: "mfoxleyx@imdb.com",
    gender: "Bigender",
  },
  {
    id: "3",
    date_time: "2021-06-21 08:11:07",
    first_name: "Tallulah",
    last_name: "Carverhill",
    email: "tcarverhilly@hao123.com",
    gender: "Non-binary",
  },
  {
    id: "1",
    date_time: "2021-12-02 10:28:57",
    first_name: "Karoline",
    last_name: "Siveter",
    email: "ksiveterz@alibaba.com",
    gender: "Bigender",
  },
  {
    id: "3",
    date_time: "2021-06-27 13:16:43",
    first_name: "Fair",
    last_name: "Sherville",
    email: "fsherville10@usgs.gov",
    gender: "Agender",
  },
  {
    id: "7",
    date_time: "2021-01-12 12:01:17",
    first_name: "Brittaney",
    last_name: "Venneur",
    email: "bvenneur11@fc2.com",
    gender: "Agender",
  },
  {
    id: "8",
    date_time: "2021-06-13 20:01:34",
    first_name: "Truman",
    last_name: "Brackstone",
    email: "tbrackstone12@washingtonpost.com",
    gender: "Polygender",
  },
  {
    id: "4",
    date_time: "2020-12-10 09:06:22",
    first_name: "Brice",
    last_name: "Wheelhouse",
    email: "bwheelhouse13@drupal.org",
    gender: "Polygender",
  },
  {
    id: "5",
    date_time: "2021-03-26 08:12:38",
    first_name: "Dominic",
    last_name: "Magrannell",
    email: "dmagrannell14@sina.com.cn",
    gender: "Polygender",
  },
  {
    id: "8",
    date_time: "2021-01-04 12:59:54",
    first_name: "Luella",
    last_name: "Nussii",
    email: "lnussii15@cbslocal.com",
    gender: "Female",
  },
  {
    id: "0",
    date_time: "2021-10-03 00:50:49",
    first_name: "Jermayne",
    last_name: "Holcroft",
    email: "jholcroft16@cloudflare.com",
    gender: "Genderqueer",
  },
  {
    id: "7",
    date_time: "2021-04-04 08:44:06",
    first_name: "Emylee",
    last_name: "Rikel",
    email: "erikel17@fotki.com",
    gender: "Genderqueer",
  },
  {
    id: "1",
    date_time: "2021-10-10 19:10:43",
    first_name: "Verne",
    last_name: "Kapiloff",
    email: "vkapiloff18@ucla.edu",
    gender: "Female",
  },
  {
    id: "3",
    date_time: "2021-10-19 19:20:22",
    first_name: "Emmalynne",
    last_name: "Crellim",
    email: "ecrellim19@barnesandnoble.com",
    gender: "Bigender",
  },
  {
    id: "9",
    date_time: "2021-06-27 08:46:46",
    first_name: "Margarethe",
    last_name: "Sellers",
    email: "msellers1a@technorati.com",
    gender: "Polygender",
  },
  {
    id: "4",
    date_time: "2021-12-07 08:39:33",
    first_name: "Damian",
    last_name: "Dreini",
    email: "ddreini1b@paginegialle.it",
    gender: "Non-binary",
  },
  {
    id: "1",
    date_time: "2021-01-03 08:06:09",
    first_name: "Trish",
    last_name: "Brizland",
    email: "tbrizland1c@oaic.gov.au",
    gender: "Bigender",
  },
  {
    id: "4",
    date_time: "2021-05-03 12:00:11",
    first_name: "Raye",
    last_name: "Vasechkin",
    email: "rvasechkin1d@constantcontact.com",
    gender: "Non-binary",
  },
  {
    id: "8",
    date_time: "2021-10-11 03:44:41",
    first_name: "Nickolaus",
    last_name: "Crevy",
    email: "ncrevy1e@1688.com",
    gender: "Agender",
  },
  {
    id: "4",
    date_time: "2021-01-30 00:32:23",
    first_name: "Hagan",
    last_name: "Punter",
    email: "hpunter1f@senate.gov",
    gender: "Genderfluid",
  },
  {
    id: "1",
    date_time: "2021-02-22 16:17:04",
    first_name: "Tedda",
    last_name: "Dodding",
    email: "tdodding1g@narod.ru",
    gender: "Genderfluid",
  },
  {
    id: "9",
    date_time: "2021-02-09 05:37:12",
    first_name: "Shir",
    last_name: "Yeabsley",
    email: "syeabsley1h@devhub.com",
    gender: "Non-binary",
  },
  {
    id: "9",
    date_time: "2021-07-02 09:40:23",
    first_name: "Sada",
    last_name: "Chown",
    email: "schown1i@ebay.co.uk",
    gender: "Non-binary",
  },
  {
    id: "2",
    date_time: "2021-06-27 15:43:37",
    first_name: "Lucinda",
    last_name: "Leale",
    email: "lleale1j@bloglovin.com",
    gender: "Polygender",
  },
  {
    id: "2",
    date_time: "2021-02-10 07:38:23",
    first_name: "Tristam",
    last_name: "Tuberfield",
    email: "ttuberfield1k@deliciousdays.com",
    gender: "Non-binary",
  },
  {
    id: "5",
    date_time: "2021-02-28 00:40:06",
    first_name: "Ezmeralda",
    last_name: "Ferrulli",
    email: "eferrulli1l@bluehost.com",
    gender: "Male",
  },
  {
    id: "0",
    date_time: "2021-02-14 00:10:56",
    first_name: "Ervin",
    last_name: "Mertgen",
    email: "emertgen1m@yale.edu",
    gender: "Agender",
  },
  {
    id: "0",
    date_time: "2021-11-01 15:10:42",
    first_name: "Waverly",
    last_name: "Aingell",
    email: "waingell1n@google.it",
    gender: "Genderfluid",
  },
  {
    id: "0",
    date_time: "2020-12-29 10:56:53",
    first_name: "Mireielle",
    last_name: "Rigolle",
    email: "mrigolle1o@list-manage.com",
    gender: "Non-binary",
  },
  {
    id: "7",
    date_time: "2021-06-12 12:35:24",
    first_name: "Charmine",
    last_name: "Lacroix",
    email: "clacroix1p@about.me",
    gender: "Male",
  },
  {
    id: "1",
    date_time: "2021-08-01 06:47:26",
    first_name: "Marcos",
    last_name: "Krochmann",
    email: "mkrochmann1q@blinklist.com",
    gender: "Bigender",
  },
  {
    id: "1",
    date_time: "2021-02-15 11:49:18",
    first_name: "Krispin",
    last_name: "Bunford",
    email: "kbunford1r@ucoz.com",
    gender: "Bigender",
  },
  {
    id: "6",
    date_time: "2021-04-22 19:06:29",
    first_name: "Minnie",
    last_name: "Geffcock",
    email: "mgeffcock1s@de.vu",
    gender: "Male",
  },
  {
    id: "9",
    date_time: "2021-05-18 23:56:10",
    first_name: "Pablo",
    last_name: "Howsley",
    email: "phowsley1t@1und1.de",
    gender: "Polygender",
  },
  {
    id: "1",
    date_time: "2021-03-12 07:36:30",
    first_name: "Melvin",
    last_name: "Henighan",
    email: "mhenighan1u@npr.org",
    gender: "Polygender",
  },
  {
    id: "1",
    date_time: "2021-01-05 06:13:08",
    first_name: "Sadie",
    last_name: "Wandrich",
    email: "swandrich1v@yellowpages.com",
    gender: "Female",
  },
  {
    id: "1",
    date_time: "2021-07-01 07:52:51",
    first_name: "Phoebe",
    last_name: "Guy",
    email: "pguy1w@istockphoto.com",
    gender: "Agender",
  },
  {
    id: "9",
    date_time: "2021-06-16 05:58:17",
    first_name: "Trixy",
    last_name: "Boldock",
    email: "tboldock1x@google.fr",
    gender: "Genderqueer",
  },
  {
    id: "9",
    date_time: "2021-04-18 16:13:12",
    first_name: "Sunny",
    last_name: "Denson",
    email: "sdenson1y@google.ru",
    gender: "Female",
  },
  {
    id: "7",
    date_time: "2021-07-22 07:54:38",
    first_name: "Maddie",
    last_name: "Watkinson",
    email: "mwatkinson1z@fc2.com",
    gender: "Genderfluid",
  },
  {
    id: "2",
    date_time: "2020-12-30 17:38:05",
    first_name: "Kimberlee",
    last_name: "Orable",
    email: "korable20@mlb.com",
    gender: "Bigender",
  },
  {
    id: "0",
    date_time: "2021-10-28 16:03:36",
    first_name: "Dale",
    last_name: "Danilchev",
    email: "ddanilchev21@senate.gov",
    gender: "Male",
  },
  {
    id: "6",
    date_time: "2021-04-02 06:50:18",
    first_name: "Isador",
    last_name: "Fenn",
    email: "ifenn22@nasa.gov",
    gender: "Male",
  },
  {
    id: "9",
    date_time: "2021-07-22 09:18:50",
    first_name: "Griff",
    last_name: "Duddin",
    email: "gduddin23@icq.com",
    gender: "Non-binary",
  },
  {
    id: "6",
    date_time: "2021-05-19 00:51:40",
    first_name: "Binny",
    last_name: "Coddrington",
    email: "bcoddrington24@house.gov",
    gender: "Male",
  },
  {
    id: "3",
    date_time: "2021-06-21 02:12:53",
    first_name: "Desi",
    last_name: "Currell",
    email: "dcurrell25@vinaora.com",
    gender: "Polygender",
  },
  {
    id: "9",
    date_time: "2021-11-27 20:17:38",
    first_name: "Malanie",
    last_name: "Judkins",
    email: "mjudkins26@4shared.com",
    gender: "Female",
  },
  {
    id: "7",
    date_time: "2021-06-16 06:05:49",
    first_name: "Ranna",
    last_name: "Leall",
    email: "rleall27@economist.com",
    gender: "Genderqueer",
  },
  {
    id: "3",
    date_time: "2021-03-08 16:02:18",
    first_name: "Josi",
    last_name: "Stacy",
    email: "jstacy28@pen.io",
    gender: "Polygender",
  },
  {
    id: "6",
    date_time: "2021-07-12 21:50:50",
    first_name: "Gisele",
    last_name: "Padgham",
    email: "gpadgham29@techcrunch.com",
    gender: "Polygender",
  },
  {
    id: "2",
    date_time: "2021-01-24 17:37:43",
    first_name: "Rozina",
    last_name: "Collingridge",
    email: "rcollingridge2a@xrea.com",
    gender: "Agender",
  },
  {
    id: "7",
    date_time: "2021-09-11 00:37:00",
    first_name: "Rici",
    last_name: "Tangye",
    email: "rtangye2b@hc360.com",
    gender: "Polygender",
  },
  {
    id: "0",
    date_time: "2021-02-07 05:04:04",
    first_name: "Nalani",
    last_name: "Arnao",
    email: "narnao2c@noaa.gov",
    gender: "Polygender",
  },
  {
    id: "4",
    date_time: "2021-06-25 23:00:29",
    first_name: "Corabelle",
    last_name: "Ponten",
    email: "cponten2d@nyu.edu",
    gender: "Genderfluid",
  },
  {
    id: "5",
    date_time: "2021-03-27 23:56:45",
    first_name: "Mil",
    last_name: "Greatham",
    email: "mgreatham2e@twitter.com",
    gender: "Polygender",
  },
  {
    id: "4",
    date_time: "2021-05-19 07:39:04",
    first_name: "Blane",
    last_name: "Hanselman",
    email: "bhanselman2f@nyu.edu",
    gender: "Polygender",
  },
  {
    id: "1",
    date_time: "2020-12-24 05:52:41",
    first_name: "Thaxter",
    last_name: "Boykett",
    email: "tboykett2g@people.com.cn",
    gender: "Genderqueer",
  },
  {
    id: "1",
    date_time: "2021-04-06 13:55:45",
    first_name: "Courtney",
    last_name: "Gainsbury",
    email: "cgainsbury2h@prlog.org",
    gender: "Male",
  },
  {
    id: "3",
    date_time: "2021-08-13 19:02:31",
    first_name: "Anne-corinne",
    last_name: "Baynam",
    email: "abaynam2i@mozilla.com",
    gender: "Bigender",
  },
  {
    id: "4",
    date_time: "2021-06-29 09:41:02",
    first_name: "Consuela",
    last_name: "Arnoult",
    email: "carnoult2j@nps.gov",
    gender: "Genderqueer",
  },
  {
    id: "9",
    date_time: "2021-01-15 06:40:27",
    first_name: "Hoebart",
    last_name: "Dovey",
    email: "hdovey2k@sina.com.cn",
    gender: "Bigender",
  },
  {
    id: "3",
    date_time: "2021-09-08 21:46:52",
    first_name: "Aundrea",
    last_name: "Santarelli",
    email: "asantarelli2l@earthlink.net",
    gender: "Bigender",
  },
  {
    id: "8",
    date_time: "2021-06-14 18:04:17",
    first_name: "Jocelyne",
    last_name: "Prendergrast",
    email: "jprendergrast2m@google.com.au",
    gender: "Agender",
  },
  {
    id: "1",
    date_time: "2020-12-13 05:14:12",
    first_name: "Coretta",
    last_name: "Eaton",
    email: "ceaton2n@about.me",
    gender: "Female",
  },
  {
    id: "9",
    date_time: "2021-05-13 09:37:24",
    first_name: "Ode",
    last_name: "Knellen",
    email: "oknellen2o@123-reg.co.uk",
    gender: "Polygender",
  },
  {
    id: "1",
    date_time: "2021-04-11 06:48:36",
    first_name: "Benton",
    last_name: "Cartledge",
    email: "bcartledge2p@sakura.ne.jp",
    gender: "Male",
  },
  {
    id: "9",
    date_time: "2021-04-16 03:27:48",
    first_name: "Murray",
    last_name: "Andryushin",
    email: "mandryushin2q@aboutads.info",
    gender: "Non-binary",
  },
  {
    id: "8",
    date_time: "2021-03-31 15:48:52",
    first_name: "Gerti",
    last_name: "Malone",
    email: "gmalone2r@deviantart.com",
    gender: "Genderfluid",
  },
];

// const mockData1 = [
//   {
//     id: 1,
//     date_time: "2020-12-15 23:30:44",
//     first_name: "Loutitia",
//     last_name: "Tomaszewicz",
//     email: "ltomaszewicz0@constantcontact.com",
//     gender: "Bigender",
//   },
//   {
//     id: 2,
//     date_time: "2021-09-25 04:48:23",
//     first_name: "Mora",
//     last_name: "Burgyn",
//     email: "mburgyn1@time.com",
//     gender: "Female",
//   },
//   {
//     id: 3,
//     date_time: "2021-03-08 11:11:07",
//     first_name: "Felice",
//     last_name: "Sorby",
//     email: "fsorby2@princeton.edu",
//     gender: "Genderqueer",
//   },
//   {
//     id: 4,
//     date_time: "2021-08-25 14:32:40",
//     first_name: "Catie",
//     last_name: "Swatridge",
//     email: "cswatridge3@bluehost.com",
//     gender: "Genderfluid",
//   },
//   {
//     id: 5,
//     date_time: "2021-01-30 11:47:45",
//     first_name: "Conrade",
//     last_name: "Connichie",
//     email: "cconnichie4@nydailynews.com",
//     gender: "Genderqueer",
//   },
//   {
//     id: 6,
//     date_time: "2021-07-22 15:44:41",
//     first_name: "Kristen",
//     last_name: "Buckney",
//     email: "kbuckney5@ucoz.ru",
//     gender: "Male",
//   },
//   {
//     id: 7,
//     date_time: "2021-10-20 22:41:11",
//     first_name: "Celestina",
//     last_name: "Warricker",
//     email: "cwarricker6@washington.edu",
//     gender: "Female",
//   },
//   {
//     id: 8,
//     date_time: "2021-02-01 23:50:16",
//     first_name: "Tawsha",
//     last_name: "Pehrsson",
//     email: "tpehrsson7@amazon.co.jp",
//     gender: "Non-binary",
//   },
//   {
//     id: 9,
//     date_time: "2021-11-23 00:41:03",
//     first_name: "Eyde",
//     last_name: "Lucas",
//     email: "elucas8@weebly.com",
//     gender: "Agender",
//   },
//   {
//     id: 10,
//     date_time: "2021-11-24 01:35:44",
//     first_name: "Mora",
//     last_name: "Clayworth",
//     email: "mclayworth9@mapy.cz",
//     gender: "Genderfluid",
//   },
// ];
// const mockData: MockData[] = require("./MOCK_DATA.json");
// const mockData: MockData[]

function App() {
  return <SimpleTable json_data={mockData2} />;
}
export default App;
